// ─── SHARED PORTFOLIO DATA ──────────────────────────────────────────────────
// Single source of truth consumed by both the Dossier view (page.tsx)
// and the Range / game view (GameView.tsx).

export const DATA = {
  name: "ABHINAV K",
  nameShort: "AK",
  title: "Software Engineer",
  subtitle: "Backend Systems · Distributed Architecture · AI Engineering",
  email: "abhinavkuwork@gmail.com",
  phone: "(716) 319-4521",
  links: {
    github: "https://github.com/Harshabhi6129/",
    linkedin: "https://www.linkedin.com/in/abhinavku6129/",
    resume: "https://drive.google.com/file/d/14GU4ES4sRr4HspjUHnl2xBfZGtXolcAS/view",
    medium: "https://medium.com/@harsha6129abhi",
    research: "https://link.springer.com/chapter/10.1007/978-981-97-6318-4_28",
  },
  companies: [
    {
      id: "wf",
      role: "Software Engineer",
      org: "Wells Fargo",
      time: "May 2025 – Present",
      location: "CA, United States",
      color: "#C8102E",
      stack: ["Spring Boot", "Apache Kafka", "Oracle 19c", "Redis", "OpenShift", "Micrometer", "Grafana"],
      headline: "Risk Evaluation & Rule Management at scale — 2–3M daily transaction events",
      points: [
        "Led Risk Evaluation and Rule Management microservices processing 2–3M daily transaction events via Spring Boot, Spring Kafka, Oracle 19c, and Redis on OpenShift at sub-second SLA.",
        "Introduced Redis-backed rule metadata cache with PostgreSQL config store and atomic version-swap refresh to handle 300+ compliance rules, reducing p95 latency from 620ms → 340ms.",
        "Enforced write-path idempotency via composite unique constraints, JPA transactional boundaries, and manual offset commit to resolve duplicate Oracle audit records from Kafka at-least-once delivery, reducing replay defects 80%.",
        "Implemented graceful shutdown, partition-aware readiness probes, and Micrometer/Grafana lag dashboards for rolling OpenShift deployments across 24+ Kafka partitions, cutting deployment latency spikes 40%.",
      ],
      metrics: [
        { label: "Daily Events", value: "3M+" },
        { label: "Latency Cut", value: "45%" },
        { label: "Defects Reduced", value: "80%" },
        { label: "Kafka Partitions", value: "24+" },
      ],
    },
    {
      id: "ibm",
      role: "Software Developer",
      org: "IBM",
      time: "July 2021 – May 2024",
      location: "India",
      color: "#1F70C1",
      stack: ["Spring Boot", "Spring Cloud", "Kafka", "PostgreSQL", "MongoDB", "AWS EKS", "gRPC", "Docker", "K8s"],
      headline: "Provisioning Orchestrator automating 1,500+ sandbox environments annually",
      points: [
        "Built Provisioning Orchestrator and Access Governance services using Spring Boot, Kafka, PostgreSQL, MongoDB, and AWS EKS, automating 1,500+ sandbox environments annually and reducing provisioning time from days to minutes.",
        "Enforced deterministic state machine in PostgreSQL with optimistic concurrency control and transactional Kafka task dispatch to handle concurrent AWS failures, reducing manual remediation 60%.",
        "Offloaded synchronous AWS SDK calls to partition-keyed Kafka workers with MongoDB execution tracking and idempotent IAM operations, improving provisioning success rates 30%.",
        "Enforced Spring Security OAuth2, JWT validation, Hibernate tenant-scoped filters, and AWS SDK expiration sweeps, reducing unauthorized access incidents 70%.",
        "Extracted Access Governance with gRPC internal validation, Kafka eventual consistency, and Kubernetes Ingress rate limiting from a monolith, reducing deployment blast radius 40%.",
        "Instrumented Micrometer timers per AWS operation and wired SNS/SQS failure fan-out for better observability, reducing MTTR 45%.",
        "Introduced Testcontainers-based PostgreSQL and Kafka integration tests in Jenkins CI, reducing release defects 50%.",
      ],
      metrics: [
        { label: "Envs Automated", value: "1,500+" },
        { label: "Access Incidents ↓", value: "70%" },
        { label: "MTTR Reduction", value: "45%" },
        { label: "Release Defects ↓", value: "50%" },
      ],
    },
  ],
  education: {
    school: "University at Buffalo",
    degree: "Master of Science · Computer Science",
    gpa: "3.7 / 4.0",
    time: "Aug 2024 – Dec 2025",
    location: "New York, USA",
    specialization: ["Distributed Systems", "Cloud Computing", "AI Systems", "OS Development", "Data Engineering"],
  },
  skillBento: [
    // lg - Top Tier
    { label: "Java", size: "lg", group: "lang" },
    { label: "Spring Boot", size: "lg", group: "framework" },
    { label: "Apache Kafka", size: "lg", group: "infra" },
    { label: "AWS", size: "lg", group: "cloud" },
    { label: "Kubernetes", size: "lg", group: "infra" },
    { label: "PostgreSQL", size: "lg", group: "db" },

    // md - Core Stack
    { label: "Python", size: "md", group: "lang" },
    { label: "React.js", size: "md", group: "framework" },
    { label: "Docker", size: "md", group: "infra" },
    { label: "MongoDB", size: "md", group: "db" },
    { label: "Terraform", size: "md", group: "infra" },
    { label: "Redis", size: "md", group: "db" },
    { label: "TypeScript", size: "md", group: "lang" },

    // sm - Specialized / Ancillary
    { label: "Node.js", size: "sm", group: "framework" },
    { label: "Spring Cloud", size: "sm", group: "framework" },
    { label: "OAuth2 / JWT", size: "sm", group: "security" },
    { label: "OpenShift", size: "sm", group: "cloud" },
    { label: "Microservices", size: "sm", group: "arch" },
    { label: "Spring Security", size: "sm", group: "security" },
    { label: "Prometheus", size: "sm", group: "obs" },
    { label: "Grafana", size: "sm", group: "obs" },
    { label: "Jenkins", size: "sm", group: "infra" },
    { label: "SQL", size: "sm", group: "lang" },
    { label: "System Design", size: "sm", group: "arch" },
    { label: "CI/CD", size: "sm", group: "arch" },
    { label: "Go", size: "sm", group: "lang" },
    { label: "Linux", size: "sm", group: "infra" },
    { label: "Oracle DB", size: "sm", group: "db" },
    { label: "RabbitMQ", size: "sm", group: "infra" },
    { label: "FastAPI", size: "sm", group: "framework" },
    { label: "gRPC", size: "sm", group: "framework" },
    { label: "ELK Stack", size: "sm", group: "obs" },
    { label: "AWS IAM", size: "sm", group: "security" },
    { label: "JUnit", size: "sm", group: "testing" },
    { label: "Agile", size: "sm", group: "arch" },
    { label: "Git", size: "sm", group: "infra" },
    { label: "JavaScript", size: "sm", group: "lang" },
    { label: "C/C++", size: "sm", group: "lang" },
    { label: "Spring WebFlux", size: "sm", group: "framework" },
    { label: "Spring Batch", size: "sm", group: "framework" },
    { label: "Spring Actuator", size: "sm", group: "framework" },
    { label: "Express", size: "sm", group: "framework" },
    { label: "GraphQL", size: "sm", group: "framework" },
    { label: "MySQL", size: "sm", group: "db" },
    { label: "DynamoDB", size: "sm", group: "db" },
    { label: "Cassandra", size: "sm", group: "db" },
    { label: "AWS SQS/SNS", size: "sm", group: "infra" },
    { label: "Azure", size: "sm", group: "cloud" },
    { label: "GCP", size: "sm", group: "cloud" },
    { label: "EC2", size: "sm", group: "cloud" },
    { label: "S3", size: "sm", group: "cloud" },
    { label: "RDS", size: "sm", group: "cloud" },
    { label: "Lambda", size: "sm", group: "cloud" },
    { label: "EKS", size: "sm", group: "cloud" },
    { label: "CloudWatch", size: "sm", group: "cloud" },
    { label: "Splunk", size: "sm", group: "obs" },
    { label: "RBAC", size: "sm", group: "security" },
    { label: "Maven", size: "sm", group: "infra" },
    { label: "Gradle", size: "sm", group: "infra" },
    { label: "Bash", size: "sm", group: "lang" },
    { label: "Postman", size: "sm", group: "infra" },
    { label: "JMeter", size: "sm", group: "testing" },
    { label: "Jira", size: "sm", group: "arch" },
    { label: "Mockito", size: "sm", group: "testing" },
    { label: "Testcontainers", size: "sm", group: "testing" },
    { label: "Jest", size: "sm", group: "testing" },
    { label: "Cucumber", size: "sm", group: "testing" },
    { label: "Scrum", size: "sm", group: "arch" },
    { label: "Event-Driven Architecture", size: "sm", group: "arch" },
  ],
  skillCategories: [
    { name: "Programming", items: ["Java", "Python", "JavaScript", "TypeScript", "Go", "SQL", "C/C++"] },
    { name: "Frameworks", items: ["Spring Boot", "Spring Cloud", "Spring WebFlux", "Spring Batch", "Spring Actuator", "React.js", "Node.js", "Express", "GraphQL", "FastAPI", "gRPC"] },
    { name: "Databases", items: ["PostgreSQL", "Oracle DB", "MySQL", "MongoDB", "DynamoDB", "Cassandra", "Redis"] },
    { name: "Streaming & Cache", items: ["Apache Kafka", "RabbitMQ", "AWS SQS/SNS", "Redis"] },
    { name: "Cloud", items: ["AWS", "Azure", "GCP", "OpenShift", "EC2", "S3", "RDS", "Lambda", "EKS", "IAM", "CloudWatch"] },
    { name: "Observability", items: ["Prometheus", "Grafana", "Micrometer", "ELK Stack", "Splunk"] },
    { name: "Security", items: ["OAuth2 / JWT", "RBAC", "AWS IAM", "Spring Security"] },
    { name: "DevOps", items: ["Docker", "Kubernetes", "Terraform", "Jenkins", "Git", "Maven", "Gradle", "Linux", "Bash", "Postman", "JMeter", "Jira"] },
    { name: "Testing", items: ["JUnit", "Mockito", "Testcontainers", "Jest", "Cucumber"] },
    { name: "Methodologies", items: ["Agile", "Scrum", "System Design", "Event-Driven Architecture", "Microservices", "CI/CD"] },
  ],
  featuredProjects: [
    {
      id: "roadmaphub",
      title: "RoadmapHub",
      blurb: "Chrome extension that turns roadmap.sh learning progress into a structured GitHub portfolio — automatically. Like LeetHub, but for learning. Detects topic completion, generates AI-enhanced summaries, and commits structured markdown to GitHub.",
      tools: ["TypeScript", "React 19", "Chrome MV3", "Vite", "Gemini AI", "GitHub OAuth", "Cloudflare Workers"],
      code: "https://github.com/Harshabhi6129/roadmaphub-extension",
      accent: "#00D4FF",
    },
    {
      id: "jobgenie",
      title: "Job Genie",
      blurb: "AI-powered talent acquisition platform. Parses JDs and ranks candidates using NLP + ML — reduces sourcing time by 80%.",
      tools: ["React.js", "FastAPI", "TensorFlow", "OpenAI", "PostgreSQL", "Docker"],
      code: "https://github.com/Harshabhi6129/Job-Genie",
      accent: "#F5A623",
    },
    {
      id: "medilink",
      title: "MediLink",
      blurb: "Production-grade collaborative clinical network. Doctors share cases, access AI insights, and democratize medical knowledge.",
      tools: ["React", "TypeScript", "Tailwind CSS", "System Design"],
      code: "https://github.com/Harshabhi6129/MediLink",
      demo: "https://medilink-rust.vercel.app/",
      accent: "#00E5A0",
    },
    {
      id: "nocode",
      title: "No-Code ML Platform",
      blurb: "Automated ML fine-tuning and model recommendation. Orchestrates distributed GPU-backed training workloads — reduces setup time by 50%.",
      tools: ["FastAPI", "PyTorch", "HuggingFace", "Google Gemini", "DynamoDB", "S3", "Docker", "AWS EC2", "React", "WebSockets"],
      accent: "#7C6EFA",
    },
  ],
  moreProjects: [
    {
      title: "Prompt Refinement & AI Chat",
      blurb: "Full-stack prompt designer with real-time chat, MongoDB storage, and document parsing.",
      tools: ["React", "Node.js", "MongoDB", "OpenAI"],
    },
    {
      title: "PINTOS OS Development",
      blurb: "Enhanced Pintos (C, x86) with priority donation, MLFQ, sync primitives. 90%+ test coverage.",
      tools: ["C", "x86 Assembly"],
    },
    {
      title: "Sentiment Analysis",
      blurb: "Airline tweet classifier with 84.6% accuracy. TF-IDF, SMOTE, sarcasm detection.",
      tools: ["Python", "NLP", "ML"],
      code: "https://github.com/Harshabhi6129/Sentiment-Analysis-with-Tone-Detection",
    },
    {
      title: "Real-Time AI Virtual Mouse",
      blurb: "Hands-free cursor control via CV + DL. Gesture recognition and virtual keyboard.",
      tools: ["Python", "OpenCV", "Deep Learning"],
      code: "https://github.com/Harshabhi6129/Real-Time-AI-Virtual-Mouse-System-Using-Deep-Learning",
    },
    {
      title: "Persona AI",
      blurb: "Conversational agent with memory + ChromaDB context retrieval and adaptive tone.",
      tools: ["OpenAI", "ChromaDB", "Streamlit"],
      code: "https://github.com/Harshabhi6129/Persona_AI",
    },
    {
      title: "Next-Word Prediction (LSTM-GRU)",
      blurb: "Sequence model demo with Streamlit interface.",
      tools: ["Python", "LSTM", "GRU"],
      code: "https://github.com/Harshabhi6129/Next-Word-Prediction-using-LSTM-GRU",
    },
  ],
  certifications: [
    {
      title: "AWS Certified Solutions Architect – Associate",
      issuer: "Amazon Web Services",
      issued: "Mar 2024",
      expires: "Mar 2027",
      link: "#",
      tier: "gold",
    },
    {
      title: "AWS Certified Developer – Associate",
      issuer: "Amazon Web Services",
      issued: "Feb 2024",
      expires: "Feb 2027",
      link: "#",
      tier: "gold",
    },
    {
      title: "AWS Certified ML Engineer – Associate",
      issuer: "Amazon Web Services",
      issued: "May 2025",
      expires: "May 2028",
      link: "https://www.credly.com/badges/481a3796-1871-4387-8933-3351381f80af/linked_in_profile",
      tier: "gold",
    },
    {
      title: "Career Essentials in Generative AI",
      issuer: "Microsoft & LinkedIn",
      issued: "Sep 2024",
      link: "https://www.linkedin.com/learning/certificates/868ae44056adbc0bf99c92c394ec3d1187d484883cc00c6758d689658bbf46d7",
      tier: "silver",
    },
    {
      title: "BCG — GenAI",
      issuer: "BCG X",
      issued: "Jan 2025",
      link: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/SKZxezskWgmFjRvj9/gabev3vXhuACr48eb_SKZxezskWgmFjRvj9_o9Qv8ETNTrDdS37xy_1736139681637_completion_certificate.pdf",
      tier: "silver",
    },
    {
      title: "Tata Group — Data Visualisation",
      issuer: "Tata Group",
      issued: "Jan 2025",
      link: "https://forage-uploads-prod.s3.amazonaws.com/completion-certificates/ifobHAoMjQs9s6bKS/MyXvBcppsW2FkNYCX_ifobHAoMjQs9s6bKS_o9Qv8ETNTrDdS37xy_1737607135331_completion_certificate.pdf",
      tier: "silver",
    },
  ],
};

export const groupColors: Record<string, string> = {
  lang: "#F5A623",
  framework: "#00D4FF",
  infra: "#7C6EFA",
  cloud: "#FF6B6B",
  db: "#00E5A0",
  security: "#FFB347",
  arch: "#C084FC",
  obs: "#34D399",
  ai: "#F472B6",
};
